export const GET_COUNTRIES = "GET_COUNTRIES"
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const ORDER_BY_ALPHABET = "ORDER_BY_ALPHABET";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const POST_ACTIVITY = "POST_ACTIVITY"
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME"